### ISSUE TITLE
iCloud_FMF ERROR

### ISSUE THREAD

**Issue by xSynthx** [manwhoami/Bella#14]
I get this error when I run `iCloud_FMF`... I have root also
```
Traceback (most recent call last):
  File "/Library/Containers/.bella/Bella", line 1997, in bella
    send_msg(heard_it_from_a_friend_who(dsid, token, cardData), True)
  File "/Library/Containers/.bella/Bella", line 690, in heard_it_from_a_friend_who
    for y in x["locations"]:#[0]["location"]["address"]:
KeyError: 'locations'
```

**Comment by manwhoami** [comment]
I added some better error handling to this function. It will return a message if it cannot find any locations in the response dictionary. Let me know about any issues
