### ISSUE TITLE
Bella doesn't support UTF-8 encoding

### ISSUE THREAD

**Issue by JPaulMora** [manwhoami/Bella#3]
````
[*] Using [/Users/test/Library/Keychains/login.keychain] as keychain.
[*] Decrypting token plist
	[/Users/test/Library/Application Support/iCloud/Accounts/1001046718]
[-] Malfunction:

Traceback (most recent call last):
  File "/Library/Containers/.bella/Bella", line 1837, in bella
    tokenForce()
  File "/Library/Containers/.bella/Bella", line 1576, in tokenForce
    logged = updateDB(encrypt(tokz), 'mme_token') #update the DB....
  File "/Library/Containers/.bella/Bella", line 186, in encrypt
    data = base64.b64encode(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 53, in b64encode
    encoded = binascii.b2a_base64(s)[:-1]
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 36: ordinal not in range(128)

````

**Comment by manwhoami** [comment]
Interesting, I wonder if it is retrieving the correct decryption key from the keychain? Your Auth Token shouldn't have any unicode in it. 

If you run this program here `https://github.com/manwhoami/MMeTokenDecrypt` does it return a token successfully?

**Comment by JPaulMora** [comment]
Thanks for your quick response, will try MMETD and report back

**Comment by manwhoami** [comment]
Closing due to inactivity. Error is not related to lack of UTF encoding, as the token is pure ASCII.

**Comment by JPaulMora** [comment]
Hey I found this: http://stackoverflow.com/questions/19833440/unicodeencodeerror-ascii-codec-cant-encode-character-u-xe9-in-position-7#19833471

**Comment by manwhoami** [comment]
If you dig into the source code of Bella, you'll see that all communications between Bella and the CC are serialized. Unicode errors will only be raised in Bella ***if something else is already going wrong***.

In this case, something went wrong with the token extraction. The token decryption failed [likely due to a bad key], and it returned some binary junk. This junk was attempted to be decoded in base64, but because it is not base64 (which a proper token extraction would yield), it throws an error. Although it looks like it is a Unicode error, it is really something else! This can get quite confusing, so don't let it trip you up too much.

I suspect that the token decryption failed for you because of a [possibly] incorrect keychain. I have updated Bella to attempt to decrypt the most recently updated keychain file. You can try this and let me know if it resolves the issue.

**Comment by JPaulMora** [comment]
Update: ok, I forgot to mention.. this error was displayed in Ubuntu 16 server, and it looks like the python environment is causing this error. by trying out the commands and features, I noticed you can't press "b" (as to type "bella_info") which is [another problem on its own](http://superuser.com/questions/297527/cant-type-the-b-letter-in-python-shell-in-os-x), that, again,  points to how python sets up its runtime configuration.

**Comment by manwhoami** [comment]
I believe I pushed a fix for this a few updates ago. Are you running the latest CC?

**Comment by JPaulMora** [comment]
OK, can confirm it works now. Updating my fork
