### ISSUE TITLE
Documentation on removal

### ISSUE THREAD

**Issue by killingit57** [manwhoami/Bella#45]
Hi there,

I've been doing some local/remote testing. The remote remove works well but when I go to reinstall locally, I get prompted with options on if I'd like to reinstall Bella. This makes running an automated attack w/ a Rubber Ducky more challenging. Can you document a full uninstall (commands to run or script) or change this behavior? I recognize this might be an edge case but I wanted to ask.
Thanks!

**Edit: Solved below. I was calling Control Center.py from a different location and not from it's local folder. That was the issue there.**
Also I've been getting this error from the C&C when attempting to connect to clients who have had multiple reinstalls: 
`Accepting Connection from [target] at [123.45.678.9]
Payloads requested. Sending payloads...
Traceback (most recent call last):
  File "Bella/Control Center.py", line 736, in <module>
    main()
  File "Bella/Control Center.py", line 311, in main
    with open('Payloads/payloads.txt', 'rb') as content:
IOError: [Errno 2] No such file or directory: 'Payloads/payloads.txt'`

**Comment by killingit57** [comment]
Working more on this - I believe the first issue is related to my local machine and not to Bella. Closing this issue.
