### ISSUE TITLE
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:590)

### ISSUE THREAD

**Issue by iownbish** [manwhoami/Bella#54]
Listening for clients over port [5900]                      
	     [####################################################] 
EOF occurred in violation of protocol (_ssl.c:590)
Traceback (most recent call last):
  File "Control Center.py", line 804, in <module>
    main()
  File "Control Center.py", line 196, in main
    raise e
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:590)

been using the VNC port coupled with DDNS for projects outside of the LAN. i've followed up on all the suggested solutions for this error in other applications, but with no luck.

**Comment by manwhoami** [comment]
Strange, I will look into this and post back here.

**Comment by manwhoami** [comment]
Could you post your versions of OpenSSL and python SSL libraries?

**Comment by iownbish** [comment]
uh @ ~ $ openssl version
OpenSSL 0.9.8zh 14 Jan 2016
uh @ ~ $ python --version
Python 2.7.13
